dataset_parameters:
  hec_result_path: 'data/datasets/Model_01.p01.hdf'
  nodes_shape_path: 'data/datasets/geometry/cell_centers.shp'
  edges_shape_path: 'data/datasets/geometry/links.shp'

node_features:
  area          : True    # Cell area per node
  roughness     : True    # Manning's roughness
  elevation     : True    # Node elevation
  water_level   : True    # Water level at each node

edge_features:
  direction_x   : True    # Link direction along x-axis
  direction_y   : True    # Link direction along y-axis
  face_length   : True    # Link face length
  length        : True    # Link length
  slope         : True    # Link slope
  velocity      : True    # Water velocity at each link
