dataset_parameters:
  storage_mode: 'memory' # 'memory' or 'disk'
  previous_timesteps: 2
  normalize: True
  trim_from_peak_water_depth: True
  dataset_info_path: 'data/datasets/hr/dataset_info.yaml'
  feature_stats_file: 'feature_stats.yaml'

  flood_events:
    hrp03:
      root_dir: 'data/datasets/hr/hrp03'
      hec_ras_hdf_file: 'M01.p03.hdf'
      nodes_shp_file: 'cell_centers.shp'
      edges_shp_file: 'links.shp'
    hrp06:
      root_dir: 'data/datasets/hr/hrp06'
      hec_ras_hdf_file: 'M01.p06.hdf'
      nodes_shp_file: 'cell_centers.shp'
      edges_shp_file: 'links.shp'
    hrp07:
      root_dir: 'data/datasets/hr/hrp07'
      hec_ras_hdf_file: 'M01.p07.hdf'
      nodes_shp_file: 'cell_centers.shp'
      edges_shp_file: 'links.shp'
    hrp09:
      root_dir: 'data/datasets/hr/hrp09'
      hec_ras_hdf_file: 'M01.p09.hdf'
      nodes_shp_file: 'cell_centers.shp'
      edges_shp_file: 'links.shp'

  node_features:
    area          : True    # Cell area per node
    roughness     : True    # Manning's roughness
    elevation     : True    # Node elevation
    rainfall      : True    # Rainfall added per interval at each node
    water_depth   : True    # Water depth at each node

  edge_features:
    direction_x   : False   # Link direction along x-axis
    direction_y   : False   # Link direction along y-axis
    face_length   : True    # Link face length
    length        : True    # Link length
    slope         : True    # Link slope
    velocity      : True    # Water velocity at each link

training_parameters:
  num_epochs      : 10            # Number of epochs
  batch_size      : 8             # Batch size
  learning_rate   : 0.007         # learning rate
  weight_decay    : 0             # weight decay

model_parameters:
  NodeEdgeGNN:
    hidden_features: 32
    num_layers: 8
    activation: 'prelu'
    residual: True
    mlp_layers: 2
    encoder_layers: 2
    encoder_activation: 'prelu'
    decoder_layers: 2
    decoder_activation: 'prelu'
    loss_func: 'mse'
    loss_func_parameters:
      node_weight: 0.5      # Scale for water level loss
      edge_weight: 0.5      # Scale for velocity loss

  GCN:
    hidden_features: 32
    num_layers: 2
    activation: 'prelu'
    residual: True
    encoder_layers: 2
    encoder_activation: 'prelu'
    decoder_layers: 2
    decoder_activation: 'prelu'
    loss_func: 'mse'

  GAT:
    hidden_features: 32
    use_edge_features: False
    num_layers: 2
    activation: 'prelu'
    residual: True
    num_heads: 1
    concat: True
    dropout: 0.0
    add_self_loops: True
    negative_slope: 0.2
    attn_bias: True
    attn_residual: True
    encoder_layers: 2
    encoder_activation: 'prelu'
    decoder_layers: 2
    decoder_activation: 'prelu'
    loss_func: 'mse'

  GIN:
    hidden_features: 32
    num_layers: 1
    activation: 'relu'
    residual: True
    mlp_layers: 2
    eps: 0.0
    train_eps: False
    encoder_layers: 0
    encoder_activation: null
    decoder_layers: 0
    decoder_activation: null
    loss_func: 'mse'

  GraphSAGE:
    hidden_features: 32
    num_layers: 2
    activation: 'prelu'
    residual: False
    aggr: 'mean'
    normalize: False
    root_weight: True
    project: False
    bias: True
    encoder_layers: 2
    encoder_activation: 'prelu'
    decoder_layers: 2
    decoder_activation: 'prelu'
    loss_func: 'mse'

  GNNNoPassing:
    hidden_features: 32
    num_layers: 2
    activation: 'prelu'
    residual: True
    mlp_layers: 2
    encoder_layers: 2
    encoder_activation: 'prelu'
    decoder_layers: 2
    decoder_activation: 'prelu'
    loss_func: 'mse'

  MLP:
    num_layers: 2
    activation: 'prelu'
    bias: True
    residual: True
    loss_func: 'mse'
