flood_event_parameters:
  hec_ras_hdf_paths:
    hrp03: 'data/datasets/hr/M01.p03.hdf'
    hrp06: 'data/datasets/hr/M01.p06.hdf'
    hrp07: 'data/datasets/hr/M01.p07.hdf'
    hrp09: 'data/datasets/hr/M01.p09.hdf'

mesh_parameters:
  nodes_shp_path: 'data/datasets/hr/geometry/cell_centers.shp'
  edges_shp_path: 'data/datasets/hr/geometry/links.shp'

dataset_parameters:
  graph_metadata_path: 'data/graph_metadata.yaml'
  feature_metadata_path: 'data/feature_metadata.yaml'
  previous_timesteps: 2

output_parameters:
  output_dir: 'data/datasets/hr/processed/'
  dataset_info_filename: 'dataset_info.yaml'

node_features:
  area          : True    # Cell area per node
  roughness     : True    # Manning's roughness
  elevation     : True    # Node elevation
  rainfall      : True    # Rainfall added per interval at each node
  water_level   : True    # Water level at each node

edge_features:
  direction_x   : True    # Link direction along x-axis
  direction_y   : True    # Link direction along y-axis
  face_length   : True    # Link face length
  length        : True    # Link length
  slope         : True    # Link slope
  velocity      : True    # Water velocity at each link
